export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const DISHES_GET_ALL = 'DISHES_GET_ALL';
export const DISHES_GET_ALL_ERROR = 'DISHES_GET_ALL_ERROR';
export const DISH_SET_LOADING = 'DISH_SET_LOADING';
export const DISHES_SET_LOADING = 'DISHES_SET_LOADING';

export const CUSTOMERS_GET_ALL = 'CUSTOMERS_GET_ALL';
export const CUSTOMERS_SET_LOADING = 'CUSTOMERS_SET_LOADING';
export const CUSTOMER_GET_BY_ID = 'CUSTOMER_GET_BY_ID';

export const ORDERS_GET_ALL = 'ORDERS_GET_ALL';
export const ORDERS_SET_LOADING = 'ORDERS_SET_LOADING';
export const ORDER_ADD_CUSTOMER = 'ORDER_ADD_CUSTOMER';
export const ORDER_SET_TOTAL = 'ORDER_SET_TOTAL';
export const ORDER_SET_STATUS = 'ORDER_SET_STATUS';
export const ORDER_SET_STATUS_IN_LIST = 'ORDER_SET_STATUS_IN_LIST';
export const ORDER_EDIT = 'ORDER_EDIT';
export const ORDER_EDIT_DISH = 'ORDER_EDIT_DISH';
export const ORDER_ADD_DISH = 'ORDER_ADD_DISH';
export const ORDER_ADD_COMMENT = 'ORDER_ADD_COMMENT';
export const ORDER_NEW_ERRORS = 'ORDER_NEW_ERRORS';
export const ORDER_CLEAR_STORE = 'ORDER_CLEAR_STORE';

export const ORDER_SET_READY_DISH = 'ORDER_SET_READY_DISH';

export const PAYMENT_GET_ALL = 'PAYMENT_GET_ALL';
export const PAYMENT_GET_BY_ID = 'PAYMENT_GET_BY_ID';
export const PAYMENT_ADD = 'PAYMENT_ADD';
export const PAYMENT_SAVE = 'PAYMENT_SAVE';
export const PAYMENT_DELETE = 'PAYMENT_DELETE';
export const PAYMENT_CLEAR = 'PAYMENT_CLEAR';
export const PAYMENT_COUNT = 'PAYMENT_COUNT';
export const PAYMENT_REQUIRE_REFRESH = 'PAYMENT_REQUIRE_REFRESH';
export const PAYMENT_SET_SELECTED_DAYS = 'PAYMENT_SET_SELECTED_DAYS';
export const PAYMENT_SET_NUMBER_OF_SELECTED_WEEK =
  'PAYMENT_SET_NUMBER_OF_SELECTED_WEEK';
export const PAYMENT_SET_SELECTED_DAY_OF_WEEK =
  'PAYMENT_SET_SELECTED_DAY_OF_WEEK';
